Catch the error from powershell

diff --git a/.github/workflows/cluster.yml b/.github/workflows/cluster.yml
--- a/.github/workflows/cluster.yml
+++ b/.github/workflows/cluster.yml
@@ -36,15 +36,20 @@ jobs:
       - name: Execute powershell in container 
         run: |
           set -x
-          set -eo pipefail
           cd testing/development
-          COMMAND_OUTPUT=$(docker-compose exec -T lme pwsh -c "./testing/development/build_cluster.ps1" 2>&1)
-          COMMAND_EXIT_CODE=$?
+          docker-compose exec -T lme pwsh -c "./testing/development/build_cluster.ps1"
+        run: |
+          set -x
+          cd testing/development
+          COMMAND_OUTPUT=$(docker-compose exec -T lme pwsh -c "& { \
+            try { ./testing/development/build_cluster.ps1 -ErrorAction Stop } \
+            catch { Write-Error 'Build failed'; exit 1 }; \
+            exit \
+            }" 2>&1)
           echo "$COMMAND_OUTPUT"
-          if [ $COMMAND_EXIT_CODE -ne 0 ]; then
-            echo "Command failed with exit code $COMMAND_EXIT_CODE"
-            exit $COMMAND_EXIT_CODE
-          fi
+          grep -q 'Build failed' <<< "$COMMAND_OUTPUT" && exit 1
+
+
         env:
           AZURE_CLIENT_ID: ${{ env.AZURE_CLIENT_ID }}
           AZURE_SECRET: ${{ env.AZURE_SECRET }}
