Revert previous changes as they seemed to break upgrade

diff --git a/.github/workflows/cluster.yml b/.github/workflows/cluster.yml
--- a/.github/workflows/cluster.yml
+++ b/.github/workflows/cluster.yml
@@ -152,12 +152,13 @@ jobs:
               echo 'Elastic password is set'
             fi
           "
-
+      # TODO: Check this for failure and format the output
       - name: Upgrade to the version being built 
         run: |
-          set +e
+          set +e  
           cd testing/development
-          docker-compose exec -T lme pwsh -Command "& { cd /home/admin.ackbar/LME/testing; \
+          docker-compose exec -T lme pwsh -Command "& { 
+            cd /home/admin.ackbar/LME/testing; \
             \$env:AZURE_CLIENT_ID='${{ secrets.AZURE_CLIENT_ID }}'; \
             \$env:AZURE_SECRET='${{ secrets.AZURE_SECRET }}'; \
             \$env:AZURE_CLIENT_SECRET='${{ secrets.AZURE_SECRET }}'; \
@@ -165,27 +166,21 @@ jobs:
             \$env:UNIQUE_ID='${{ env.UNIQUE_ID }}'; \
             \$env:RESOURCE_GROUP='LME-pipe-${{ env.UNIQUE_ID }}'; \
             az login --service-principal -u \$env:AZURE_CLIENT_ID -p \$env:AZURE_SECRET --tenant \$env:AZURE_TENANT; \
-            \$output = az vm run-command invoke \
-              --command-id RunShellScript \
-              --name LS1 \
+            az vm run-command invoke  \
+              --command-id RunShellScript  \
+              --name LS1  \
               --resource-group \$env:RESOURCE_GROUP \
               --scripts 'export HOME=/root pwd && whoami && cd ~ \
                 && git clone https://github.com/cisagov/LME.git \
                 && cd LME \
                 && git checkout -t origin/cbaxley-194-workflows \
                 && cd testing \
-                && ./development/upgrade_lme.sh ; exit \$?'; \
-            if (\$output -notlike '*UPGRADE_SUCCESSFUL*') { \
-              Write-Host 'Upgrade failed'; \
-              exit 1; \
-            } else { \
-              Write-Host 'Upgrade successful'; \
-            } \
-            exit 0; \
+                &&  ./development/upgrade_lme.sh ;  exit \$?'; \
+            exit \$LASTEXITCODE;
           }"
           EXIT_CODE=$?
           echo "Exit code: $EXIT_CODE"
-          set -e
+          set -e  
           if [ "$EXIT_CODE" -ne 0 ]; then
             exit $EXIT_CODE
           fi
