Gets the ip for minimega and doesn't check errors

diff --git a/.github/workflows/cluster.yml b/.github/workflows/cluster.yml
--- a/.github/workflows/cluster.yml
+++ b/.github/workflows/cluster.yml
@@ -125,18 +125,17 @@ jobs:
           echo "AZURE_IP=$AZURE_IP" >> $GITHUB_ENV
           echo "Azure IP:$AZURE_IP"
           MINIMEGA_IP=$(docker compose -p ${{ env.UNIQUE_ID }} exec -T pipeline bash -c "
-              ssh lme-user@$AZURE_IP 'sudo ls -l /opt/minimega/bin/'
+              ssh lme-user@$AZURE_IP 'sudo /home/lme-user/LME/testing/v2/installers/lib/get_ip_of_machine.sh linux-runner'
           ")
-              # sudo /home/lme-user/LME/testing/v2/installers/lib/get_ip_of_machine.sh linux-runner
-          EXIT_CODE=$?
-          if [ $EXIT_CODE -ne 0 ]; then
-            echo "Failed to get Minimega IP. Exit code: $EXIT_CODE" >&2
-            exit 1
-          fi
-          if [ -z "$MINIMEGA_IP" ]; then
-            echo "Minimega IP is empty" >&2
-            exit 1
-          fi
+          # EXIT_CODE=$?
+          # if [ $EXIT_CODE -ne 0 ]; then
+          #   echo "Failed to get Minimega IP. Exit code: $EXIT_CODE" >&2
+          #   exit 1
+          # fi
+          # if [ -z "$MINIMEGA_IP" ]; then
+          #   echo "Minimega IP is empty" >&2
+          #   exit 1
+          # fi
           echo "MINIMEGA_IP=$MINIMEGA_IP" >> $GITHUB_ENV    
           echo "Azure IP:$AZURE_IP Minimega IP:$MINIMEGA_IP"
           
