Fail pipeline when commands fail

diff --git a/.github/workflows/cluster.yml b/.github/workflows/cluster.yml
--- a/.github/workflows/cluster.yml
+++ b/.github/workflows/cluster.yml
@@ -36,8 +36,15 @@ jobs:
       - name: Execute powershell in container 
         run: |
           set -x
+          set -eo pipefail
           cd testing/development
-          docker-compose exec -T lme pwsh -c "./testing/development/build_cluster.ps1"
+          COMMAND_OUTPUT=$(docker-compose exec -T lme pwsh -c "./testing/development/build_cluster.ps1" 2>&1)
+          COMMAND_EXIT_CODE=$?
+          echo "$COMMAND_OUTPUT"
+          if [ $COMMAND_EXIT_CODE -ne 0 ]; then
+            echo "Command failed with exit code $COMMAND_EXIT_CODE"
+            exit $COMMAND_EXIT_CODE
+          fi
         env:
           AZURE_CLIENT_ID: ${{ env.AZURE_CLIENT_ID }}
           AZURE_SECRET: ${{ env.AZURE_SECRET }}
