Creates the ability to build the docker image and deploy LME in a container

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -175,15 +175,26 @@ jobs:
           '
         "
 
-    - name: Deploy Ubuntu 22.04 container on Azure instance
+    - name: Build Ubuntu 22.04 container on Azure instance
       run: |
         cd testing/v2/development
         docker compose -p ${{ env.UNIQUE_ID }} exec -T pipeline bash -c "
           cd /home/lme-user/LME/testing/v2/installers && \
           IP_ADDRESS=\$(cat pipe-${{ env.UNIQUE_ID }}.ip.txt) && \
           ssh lme-user@\$IP_ADDRESS 'cd LME/docker/22.04 && \
-          sudo docker compose up -d && \
-          ./check-lme-setup.sh'
+          sudo docker compose up -d \
+          '
+        "
+
+    - name: Deploy LME on 22.04 container on Azure instance
+      run: |
+        cd testing/v2/development
+        docker compose -p ${{ env.UNIQUE_ID }} exec -T pipeline bash -c "
+          cd /home/lme-user/LME/testing/v2/installers && \
+          IP_ADDRESS=\$(cat pipe-${{ env.UNIQUE_ID }}.ip.txt) && \
+          ssh lme-user@\$IP_ADDRESS 'cd LME/docker/22.04 && \
+          sudo docker compose exec lme bash -c \"NON_INTERACTIVE=true AUTO_CREATE_ENV=true /root/LME/install.sh -i 10.1.0.5 -d\" \
+          '
         "
         
     - name: Retrieve Elastic password from Ubuntu 22.04 container
@@ -217,30 +228,30 @@ jobs:
         echo "KIBANA_PASSWORD=$KIBANA_PASSWORD"
         echo "KIBANA_PASSWORD=$KIBANA_PASSWORD" >> $GITHUB_ENV
 
-    # - name: Wait for Elasticsearch indices/data streams
-    #   run: |
-    #     cd testing/v2/development
-    #     docker compose -p ${{ env.UNIQUE_ID }} exec -T pipeline bash -c "
-    #       cd /home/lme-user/LME/testing/v2/installers && \
-    #       IP_ADDRESS=\$(cat pipe-${{ env.UNIQUE_ID }}.ip.txt) && \
-    #       ssh lme-user@\$IP_ADDRESS '
-    #         set -e
-    #         echo \"Polling for required Elasticsearch indices...\"
-    #         for i in {1..30}; do
-    #           if curl -k -u '\''elastic:${ES_PASSWORD}'\'' https://localhost:9200/_cat/indices?h=index | grep .ds-metrics-system.*; then
-    #             echo \"Required index found!\"
-    #             exit 0
-    #           fi
-    #           echo \"Not ready yet, waiting...\"
-    #           sleep 10
-    #         done
-    #         echo \"Timed out waiting for required Elasticsearch indices!\"
-    #         exit 1
-    #       '
-    #     "
-    #   env:
-    #     ES_PASSWORD: ${{ env.ES_PASSWORD }}
-    #     AZURE_IP: ${{ env.AZURE_IP }}
+    - name: Wait for Elasticsearch indices/data streams
+      run: |
+        cd testing/v2/development
+        docker compose -p ${{ env.UNIQUE_ID }} exec -T pipeline bash -c "
+          cd /home/lme-user/LME/testing/v2/installers && \
+          IP_ADDRESS=\$(cat pipe-${{ env.UNIQUE_ID }}.ip.txt) && \
+          ssh lme-user@\$IP_ADDRESS '
+            set -e
+            echo \"Polling for required Elasticsearch indices...\"
+            for i in {1..30}; do
+              if curl -k -u '\''elastic:${ES_PASSWORD}'\'' https://localhost:9200/_cat/indices?h=index | grep .ds-metrics-system.*; then
+                echo \"Required index found!\"
+                exit 0
+              fi
+              echo \"Not ready yet, waiting...\"
+              sleep 10
+            done
+            echo \"Timed out waiting for required Elasticsearch indices!\"
+            exit 1
+          '
+        "
+      env:
+        ES_PASSWORD: ${{ env.ES_PASSWORD }}
+        AZURE_IP: ${{ env.AZURE_IP }}
 
     - name: Run tests for Ubuntu 22.04 container
       env:
